-- =============================================
-- AutoCare Pro - Products with Real Images
-- Run this in Supabase SQL Editor
-- First delete old products, then insert new ones
-- =============================================

DELETE FROM products;

INSERT INTO products (name, description, category, price, stock, brand, sku, image_url, is_active) VALUES

-- ===== OILS (6 products) =====
('Castrol EDGE 5W-30 (4L)', 'Advanced full synthetic engine oil with Fluid Titanium Technology. Provides ultimate engine performance and protection under pressure.', 'oils', 2499.00, 45, 'Castrol', 'OIL-EDGE-5W30', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Motor_oil_refill_with_funnel.JPG/640px-Motor_oil_refill_with_funnel.JPG', true),
('Mobil 1 0W-40 (4L)', 'Premium full synthetic motor oil designed for high-performance engines. Excellent thermal and oxidation stability.', 'oils', 2899.00, 30, 'Mobil', 'OIL-MOB1-0W40', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Motor_oil_bottles_variousbrands.jpg/640px-Motor_oil_bottles_variousbrands.jpg', true),
('Shell Helix Ultra 5W-40 (4L)', 'Fully synthetic motor oil with PurePlus Technology for ultimate engine cleanliness and protection.', 'oils', 2699.00, 35, 'Shell', 'OIL-SHELL-5W40', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/SIGAUS_aceite.jpg/640px-SIGAUS_aceite.jpg', true),
('Valvoline SynPower 5W-30 (1L)', 'Full synthetic engine oil for modern turbocharged engines. Excellent fuel economy.', 'oils', 799.00, 60, 'Valvoline', 'OIL-VAL-5W30-1L', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Motor_Oils.jpg/640px-Motor_Oils.jpg', true),
('Motul 8100 X-cess 5W-40 (5L)', '100% synthetic engine oil for powerful and recent cars. Suitable for turbocharged and multi-valve engines.', 'oils', 3499.00, 20, 'Motul', 'OIL-MOT-5W40-5L', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Motor_oil_refill_with_funnel.JPG/640px-Motor_oil_refill_with_funnel.JPG', true),
('Liqui Moly 10W-40 (1L)', 'Semi-synthetic motor oil with MoS2 anti-friction additive. Ideal for older engines.', 'oils', 599.00, 80, 'Liqui Moly', 'OIL-LM-10W40-1L', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Motor_oil_bottles_variousbrands.jpg/640px-Motor_oil_bottles_variousbrands.jpg', true),

-- ===== FILTERS (5 products) =====
('Bosch Oil Filter - Premium', 'High-quality spin-on oil filter with anti-drainback valve. Fits most sedan and SUV models.', 'filters', 349.00, 90, 'Bosch', 'FIL-BOSCH-OIL', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Kfz-oelfilter-muenze.jpg/640px-Kfz-oelfilter-muenze.jpg', true),
('Mann Air Filter - Standard', 'Premium air filter element for improved engine breathing and fuel efficiency. High dust-holding capacity.', 'filters', 499.00, 70, 'Mann', 'FIL-MANN-AIR', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Air_filter%2C_opel_astra%282%29.JPG/640px-Air_filter%2C_opel_astra%282%29.JPG', true),
('K&N High-Flow Air Filter', 'Reusable high-performance air filter. Washable and lasts up to 80,000 km between servicing.', 'filters', 1999.00, 25, 'K&N', 'FIL-KN-AIRFLOW', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Air_filter%2C_opel_astra%281%29.JPG/640px-Air_filter%2C_opel_astra%281%29.JPG', true),
('Denso Cabin Air Filter', 'Electrostatic cabin air filter removes pollen, dust, and odors. Keeps cabin air fresh and clean.', 'filters', 399.00, 55, 'Denso', 'FIL-DENSO-CABIN', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Dirty-air-filter.jpg/640px-Dirty-air-filter.jpg', true),
('Mahle Oil Filter Cartridge', 'OE quality replacement oil filter cartridge for European vehicles. Superior filtration efficiency.', 'filters', 449.00, 65, 'Mahle', 'FIL-MAHLE-OIL', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Cartridge_filter.jpg/640px-Cartridge_filter.jpg', true),

-- ===== BRAKES (5 products) =====
('Brembo Ceramic Front Brake Pads', 'High-performance ceramic brake pads for reliable stopping power. Low dust, low noise technology.', 'brakes', 1899.00, 35, 'Brembo', 'BRK-BREM-FRT', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Disk_brake_dsc03682.jpg/640px-Disk_brake_dsc03682.jpg', true),
('Bosch Rear Brake Pads Set', 'Quality rear brake pads with built-in anti-noise shims. Excellent wet and dry braking performance.', 'brakes', 1499.00, 40, 'Bosch', 'BRK-BOSCH-RR', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Ventilated_Plain_%28Smooth%29_Brake_Rotor_Parts.jpg/640px-Ventilated_Plain_%28Smooth%29_Brake_Rotor_Parts.jpg', true),
('EBC Red Stuff Brake Pads', 'Fast-street and track-day ceramic brake pads. Superb stopping power with progressive feel.', 'brakes', 2499.00, 20, 'EBC', 'BRK-EBC-RED', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/AMG_Carbon_Ceramic_brake..JPG/640px-AMG_Carbon_Ceramic_brake..JPG', true),
('Brembo Ventilated Brake Disc (Front)', 'Precision-machined ventilated brake disc rotor. Superior heat dissipation for consistent braking.', 'brakes', 3999.00, 15, 'Brembo', 'BRK-DISC-FRT', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Disk_brake_dsc03682.jpg/640px-Disk_brake_dsc03682.jpg', true),
('Brake Fluid DOT 4 (1L)', 'High-boiling-point synthetic brake fluid. Suitable for ABS and ESP systems.', 'brakes', 399.00, 70, 'Bosch', 'BRK-FLUID-DOT4', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Ventilated_Plain_%28Smooth%29_Brake_Rotor_Parts.jpg/640px-Ventilated_Plain_%28Smooth%29_Brake_Rotor_Parts.jpg', true),

-- ===== ENGINE (5 products) =====
('NGK Iridium Spark Plugs (Set of 4)', 'Iridium-tipped spark plugs for better ignition, smoother idle, and improved fuel efficiency. 60,000 km life.', 'engine', 1299.00, 50, 'NGK', 'ENG-NGK-IRID-4', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Spark-plug01.jpeg/640px-Spark-plug01.jpeg', true),
('Bosch Platinum Spark Plugs (Set of 4)', 'Platinum center electrode for consistent performance. Fine-wire design for quick starts.', 'engine', 899.00, 55, 'Bosch', 'ENG-BOSCH-PLAT-4', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Sparkplug3.jpg/640px-Sparkplug3.jpg', true),
('Denso Twin Tip Spark Plugs (Set of 4)', 'Dual ground electrode design for longer life and consistent spark. OE quality replacement.', 'engine', 999.00, 45, 'Denso', 'ENG-DENSO-TT-4', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Spark_plugs_old_and_replacement_7058.JPG/640px-Spark_plugs_old_and_replacement_7058.JPG', true),
('Timing Belt Kit with Water Pump', 'Complete timing belt replacement kit. Includes belt, tensioner, idler pulley, and water pump.', 'engine', 4999.00, 12, 'Gates', 'ENG-TIMING-KIT', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Buj%C3%ADa_Bosch_Yttrium_Super_Plus.JPG/640px-Buj%C3%ADa_Bosch_Yttrium_Super_Plus.JPG', true),
('Engine Drive Belt (V-Belt)', 'Premium EPDM rubber drive belt for alternator, power steering, and AC compressor.', 'engine', 599.00, 40, 'Continental', 'ENG-VBELT', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Spark-plug01.jpeg/640px-Spark-plug01.jpeg', true),

-- ===== ELECTRICAL (5 products) =====
('Amaron Pro 60Ah Car Battery', 'Maintenance-free car battery with patented SilvenX alloy. 60-month warranty.', 'electrical', 4999.00, 20, 'Amaron', 'ELEC-BAT-60AH', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Photo-CarBattery.jpg/640px-Photo-CarBattery.jpg', true),
('Exide Mileage 45Ah Battery', 'Long-lasting car battery designed for Indian driving conditions. Factory charged, ready to install.', 'electrical', 3799.00, 25, 'Exide', 'ELEC-BAT-45AH', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Photo-CarBattery.jpg/640px-Photo-CarBattery.jpg', true),
('Bosch Alternator Assembly', 'OE-quality alternator for reliable charging. High output 90A for modern vehicle electrical demands.', 'electrical', 6999.00, 8, 'Bosch', 'ELEC-ALT-90A', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/CrocodileClamponBattery.jpg/640px-CrocodileClamponBattery.jpg', true),
('Car Fuse Box Kit (120 pcs)', 'Complete blade fuse assortment kit with fuse puller. Includes 5A to 40A fuses for all circuits.', 'electrical', 349.00, 60, 'Generic', 'ELEC-FUSE-KIT', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/CrocodileClamponBattery.jpg/640px-CrocodileClamponBattery.jpg', true),
('Jump Starter Power Bank 12000mAh', 'Portable jump starter with USB power bank. Starts engines up to 6.0L petrol. LED flashlight included.', 'electrical', 3499.00, 18, 'Generic', 'ELEC-JUMP-12K', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Photo-CarBattery.jpg/640px-Photo-CarBattery.jpg', true),

-- ===== FLUIDS (4 products) =====
('Shell Coolant Ready-Mix (1L)', 'Ready-to-use coolant/antifreeze for optimal engine temperature management. Protects to -37°C.', 'fluids', 399.00, 75, 'Shell', 'FLD-COOL-1L', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Antifreeze_in_the_radiator.jpg/640px-Antifreeze_in_the_radiator.jpg', true),
('Power Steering Fluid (500ml)', 'Premium power steering fluid compatible with most vehicles. Prevents seal wear and reduces noise.', 'fluids', 299.00, 65, 'Prestone', 'FLD-PS-500ML', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Antifreeze_in_the_radiator.jpg/640px-Antifreeze_in_the_radiator.jpg', true),
('Windshield Washer Fluid (2L)', 'Premium glass cleaning fluid with anti-streak formula. Removes bugs, grime, and road film.', 'fluids', 199.00, 100, 'Rain-X', 'FLD-WASH-2L', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Antifreeze_in_the_radiator.jpg/640px-Antifreeze_in_the_radiator.jpg', true),
('Transmission Fluid ATF (1L)', 'Automatic transmission fluid for smooth shifting. Compatible with multi-vehicle applications.', 'fluids', 549.00, 50, 'Castrol', 'FLD-ATF-1L', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/SIGAUS_aceite.jpg/640px-SIGAUS_aceite.jpg', true),

-- ===== LIGHTING (4 products) =====
('Philips LED Headlight H4 (Pair)', 'Ultinon Pro LED headlight bulbs. 200% brighter, 6000K cool white, plug-and-play installation.', 'lighting', 2499.00, 30, 'Philips', 'LIT-LED-H4', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/2014_Toyota_Corolla_LED_Headlight.jpg/640px-2014_Toyota_Corolla_LED_Headlight.jpg', true),
('Osram H7 Halogen Bulbs (Pair)', 'Night Breaker Laser H7 halogen bulbs. Up to 150% more brightness for safer night driving.', 'lighting', 899.00, 45, 'Osram', 'LIT-H7-HAL', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/H7_IMG_1246.JPG/640px-H7_IMG_1246.JPG', true),
('LED Fog Light Bulbs H11 (Pair)', 'High-power LED fog light bulbs. 3000K warm white for improved visibility in rain and fog.', 'lighting', 1299.00, 35, 'Philips', 'LIT-FOG-H11', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/H4_IMG_1269.JPG/640px-H4_IMG_1269.JPG', true),
('LED Interior Light Kit (8 pcs)', 'Complete car interior LED light upgrade kit. Includes dome, map, trunk, and license plate bulbs.', 'lighting', 699.00, 50, 'Generic', 'LIT-INT-KIT', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Lincoln_xenon_headlamp.jpg/640px-Lincoln_xenon_headlamp.jpg', true),

-- ===== TIRES (4 products) =====
('MRF ZVTV 185/65 R15 Tire', 'All-season radial tire with optimized tread pattern for Indian roads. Excellent wet grip.', 'tires', 3999.00, 20, 'MRF', 'TIRE-MRF-185', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Assorted_stacked_automotive_tires.jpg/640px-Assorted_stacked_automotive_tires.jpg', true),
('CEAT Milaze 175/65 R14 Tire', 'Fuel-efficient tire with low rolling resistance. Long tread life and comfortable ride.', 'tires', 3499.00, 25, 'CEAT', 'TIRE-CEAT-175', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Large_tyre.jpg/640px-Large_tyre.jpg', true),
('Apollo Alnac 4G 195/55 R16 Tire', 'Premium touring tire with silica compound. Superior wet braking and fuel efficiency.', 'tires', 4499.00, 16, 'Apollo', 'TIRE-APL-195', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Assorted_stacked_automotive_tires.jpg/640px-Assorted_stacked_automotive_tires.jpg', true),
('Bridgestone Turanza 205/55 R16', 'Premium grand touring tire. Quiet ride, excellent grip, and long tread life for sedans.', 'tires', 5999.00, 12, 'Bridgestone', 'TIRE-BS-205', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Large_tyre.jpg/640px-Large_tyre.jpg', true),

-- ===== ACCESSORIES (8 products) =====
('Bosch Aerotwin Wiper Blades (Pair)', 'Flat-blade windshield wipers with natural rubber element. Streak-free wiping in all weather.', 'accessories', 799.00, 50, 'Bosch', 'ACC-WIPER-PAIR', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/2008-04-24_Windshield_wiper_parts.jpg/640px-2008-04-24_Windshield_wiper_parts.jpg', true),
('Car Phone Mount - Magnetic', 'Universal magnetic car phone mount with 360-degree rotation. Dashboard and air-vent compatible.', 'accessories', 499.00, 70, 'Generic', 'ACC-PHONE-MT', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/2008-04-24_Windshield_wiper_parts.jpg/640px-2008-04-24_Windshield_wiper_parts.jpg', true),
('Dash Cam 1080p Full HD', 'Full HD dash camera with 170° wide angle, night vision, loop recording, G-sensor, and parking monitor.', 'accessories', 3999.00, 15, 'Generic', 'ACC-DASHCAM-HD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/2008-04-24_Windshield_wiper_parts.jpg/640px-2008-04-24_Windshield_wiper_parts.jpg', true),
('Premium PU Leather Seat Cover Set', 'Universal fit premium seat covers. Waterproof, breathable, easy installation. Full set for 5 seats.', 'accessories', 3499.00, 22, 'Generic', 'ACC-SEAT-CVR', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/2008-04-24_Windshield_wiper_parts.jpg/640px-2008-04-24_Windshield_wiper_parts.jpg', true),
('Anti-Slip Steering Wheel Cover', 'Genuine leather steering wheel cover. Anti-slip grip, breathable, universal 38cm diameter.', 'accessories', 449.00, 55, 'Generic', 'ACC-STR-CVR', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/2008-04-24_Windshield_wiper_parts.jpg/640px-2008-04-24_Windshield_wiper_parts.jpg', true),
('Car Floor Mats Set (4 pcs)', 'Heavy-duty rubber floor mats. All-weather protection, anti-slip backing, easy to clean.', 'accessories', 999.00, 40, 'Generic', 'ACC-FLOOR-MAT', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/2008-04-24_Windshield_wiper_parts.jpg/640px-2008-04-24_Windshield_wiper_parts.jpg', true),
('Car Sunshade Windshield Cover', 'Foldable UV protection sunshade. Reflective material keeps car cool. Universal fit.', 'accessories', 349.00, 65, 'Generic', 'ACC-SUNSHADE', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/2008-04-24_Windshield_wiper_parts.jpg/640px-2008-04-24_Windshield_wiper_parts.jpg', true),
('Car Trunk Organizer', 'Collapsible trunk storage organizer with multiple compartments. Keeps cargo neat and secure.', 'accessories', 799.00, 35, 'Generic', 'ACC-TRUNK-ORG', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/2008-04-24_Windshield_wiper_parts.jpg/640px-2008-04-24_Windshield_wiper_parts.jpg', true),

-- ===== TOOLS (4 products) =====
('Portable Tire Inflator 12V', 'Digital tire inflator with auto shut-off at preset pressure. LCD display, LED light, 150 PSI max.', 'tools', 2199.00, 28, 'Generic', 'TOOL-INFLATOR', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Large_tyre.jpg/640px-Large_tyre.jpg', true),
('Car Emergency Tool Kit', 'Complete roadside emergency kit with jumper cables, tow rope, flashlight, first aid, and reflective triangle.', 'tools', 1499.00, 30, 'Generic', 'TOOL-EMRG-KIT', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/CrocodileClamponBattery.jpg/640px-CrocodileClamponBattery.jpg', true),
('Hydraulic Jack 2-Ton', 'Compact hydraulic floor jack. 2-ton capacity, easy lift for cars and SUVs. Includes carry case.', 'tools', 2999.00, 15, 'Generic', 'TOOL-JACK-2T', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Assorted_stacked_automotive_tires.jpg/640px-Assorted_stacked_automotive_tires.jpg', true),
('Torque Wrench 1/2" Drive', 'Professional torque wrench with 28-210 Nm range. Click-type mechanism for accurate tightening.', 'tools', 1999.00, 20, 'Generic', 'TOOL-TORQUE', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Kfz-oelfilter-muenze.jpg/640px-Kfz-oelfilter-muenze.jpg', true);
